Refactor Git Repos
KSP-CKAN/NetKAN-Infra pull request #288
Opened 2023-03-27 09:33 UTC by techman83

Many assumptions around branches and repos were made early on, since then we moved a lot of the common repo actions into relevant classes. This furthers that work and replaces all direct branch access with methods that automatically figure out the primary branch of the repo. Tests updated to reference 'main'

It is intended that #283 is reviewed and merged first, then once happy we can move onto this in preparation for adding KSP2 config. We will be able to follow soon after by renaming master -> main for the existing KSP repos.

2023-04-07 12:41 UTC, HebaruSan commented on netkan/netkan/spacedock_adder.py
> +            self.nk_repo.push_remote_branch(branch_name)
```suggestion
```

Bad merge, this block shouldn't be here (deleted in #291, we use `with self.nk_repo.change_branch` now).

2023-04-07 12:48 UTC, HebaruSan requested changes
One comment about resurrected code in SpaceDockAdder aside, this looks solid and ready to merge. 🎉

2023-04-08 03:42 UTC, HebaruSan approved these changes
Looks good, let's go with this. 🏍️

2023-04-08 03:42 UTC, techman83 commented
Resolved the bad merge conflict resolution, and removed all the reformatting. I think I'd like to switch to black for the project, but I'd rather not mix in formatting with refactoring.

2023-04-08 03:49 UTC, merged